### PR TITLE
WIP: Syntax updates

### PR DESCRIPTION
**Pull request by Naddiseo**
This is a naive first pass through the syntax to see where the type hints would need to go. I've probably also missed a few places.

I'm still also missing the actual syntax for `TypeHint`

I couple things that need thinking though:
- Rest and Spread, do they need hinting?
- Single argument lambdas: `arg type => 1` what does `type` refer to?
- Casting, if any.

### CODE REVIEW

**Comment by Naddiseo** [comment]
Regarding lambdas: I think requiring parenthesis would be the best alternate:

``` javascript
var fn = (arg ArgType) RetType => 1
```

**Comment by lukescott** [comment]
@Naddiseo thank you! Sorry I didn't get to this sooner. I've been out sick the past couple days. Is this ready to merge?

Those are some good points. I also saw some other good questions in some other issues as well. 

Regarding lambdas, I would agree that requiring parentheses for type hinting makes sense. With rest, I would think that the same type is used for every argument, so `, ...numbers Number`. Casting sort of already exists, like `Number("5")` - don't think we need anything beyond that.

We should probably track these things in individual issues though.

**Comment by Naddiseo** [comment]
@lukescott, it's probably good enough to merge as a WIP document. I'll file issues for each of the TODOs.

**Comment by lukescott** [comment]
@Naddiseo sounds good! Merged.

**Pull request merged**
